---
- name: restart puppet
  service:
    name: puppet
    state: restarted
  when: ansible_os_family == "Redhat"

- name: restart puppet server
  service:
    name: puppetserver
    state: restarted
  when: ansible_os_family == "Debian"
