---
user: "masum"
git_username: "masumndc1"
git_repo: "puppet-control"
puppet_server: "puppetserver"
puppet_server_ip: "10.187.242.28"
install_puppet7: true
install_puppet8: false
deb_package:
  - tree
  - openjdk-17-jdk
  - python3-pip
  - net-tools
  - iputils-ping
  - git
  - vim
  - wget
  - gcc
  - gpg
  - ntp
  - ntpdate
  - firewalld
  - python3-firewall
rpm_package:
  - epel-release
  - tree
  - net-tools
  - chrony
  - python3-libselinux
  - python3-firewall
  - firewalld
  - selinux-policy
port:
  - "8140/tcp"
puppet_rpm_key: "https://yum.puppet.com/RPM-GPG-KEY-puppet"
puppet7_rpm_el9: "https://yum.puppet.com/puppet7/el/9/x86_64/puppet7-release-7.0.0-21.el9.noarch.rpm"
puppet8_rpm_el9: "https://yum.puppet.com/puppet8/el/9/x86_64/puppet8-release-1.0.0-9.el9.noarch.rpm"
puppet7_release_debian12: "https://apt.puppet.com/puppet7-release-bookworm.deb"
puppet7_release_ubu22: "https://apt.puppet.com/puppet7-release-jammy.deb"
puppet8_release_debian12: "https://apt.puppet.com/puppet8-release-bookworm.deb"
puppet8_release_ubu22: "https://apt.puppet.com/puppet8-release-jammy.deb"
